/**
 * Print the tier migration for the current fixture roster.
 *
 * The fixture is deterministic, so the database seed is derivable from it.
 * Hand-maintaining both is how they drift, and a drifted seed empties the
 * floor the day VITE_SUPABASE_URL is set — which is exactly the failure
 * 0002_seed_roster.sql exists to prevent.
 *
 * Usage:
 *   npm run roster > supabase/migrations/0004_broker_tier.sql
 *
 * Bundled through esbuild for the same reason make-social.mjs is: the lib
 * uses the "@/" alias, which plain node cannot resolve.
 */

import { execSync } from "node:child_process"
import { rmSync } from "node:fs"
import { fileURLToPath } from "node:url"

const root = fileURLToPath(new URL("..", import.meta.url))
const bundle = `${root}.roster-bundle.mjs`

// Through a shell rather than execFileSync: npx resolves to npx.cmd on
// Windows, and spawning a .cmd directly is EINVAL on current Node.
execSync(
  `npx esbuild src/lib/brokers.ts --bundle --format=esm ` +
    `--alias:@=./src --outfile="${bundle}" --log-level=error`,
  { cwd: root, stdio: ["inherit", "inherit", "inherit"] }
)

const { ROSTER } = await import(`file://${bundle.split("\\").join("/")}`)

rmSync(bundle, { force: true })

const q = (s) => `'${String(s).replace(/'/g, "''")}'`

process.stdout.write(`-- PLANCKBITS — broker tier.
--
-- GENERATED by scripts/dump-roster.mjs. Do not hand-edit; regenerate it:
--   npm run roster > supabase/migrations/0004_broker_tier.sql
--
-- tier is nullable so this is safe to apply before anything writes it, and
-- rowToBroker falls back to 'common' for rows written earlier. A broker with
-- no fur would be a hole in the floor; a common-looking one is not.
--
-- TIER IS COSMETIC. It drives fur, ground and garment palette and nothing
-- else. Nothing here or downstream may let it touch nerve, latency or
-- coverage.
--
-- Idempotent, so re-running it is safe.

do $$
begin
  if not exists (select 1 from pg_type where typname = 'tier_id') then
    create type tier_id as enum ('common', 'uncommon', 'rare', 'epic', 'legendary');
  end if;
end
$$;

alter table brokers add column if not exists tier tier_id;

`)

for (const b of ROSTER) {
  process.stdout.write(`update brokers set tier = ${q(b.tier)} where id = ${q(b.id)};\n`)
}

const counts = new Map()
for (const b of ROSTER) counts.set(b.tier, (counts.get(b.tier) ?? 0) + 1)
const summary = [...counts.entries()].map(([k, v]) => `${k} ${v}`).join(", ")
process.stdout.write(`\n-- Founding floor: ${summary}.\n`)
