-- APEBITS — broker tier.
--
-- GENERATED by scripts/dump-roster.mjs. Do not hand-edit; regenerate it:
--   npm run roster > supabase/migrations/0004_broker_tier.sql
--
-- tier is nullable so this is safe to apply before anything writes it, and
-- rowToBroker falls back to 'common' for rows written earlier. A broker with
-- no fur would be a hole in the floor; a common-looking one is not.
--
-- TIER IS COSMETIC. It drives fur, ground and garment palette and nothing
-- else. Nothing here or downstream may let it touch nerve, latency or
-- coverage.
--
-- Idempotent, so re-running it is safe.

do $$
begin
  if not exists (select 1 from pg_type where typname = 'tier_id') then
    create type tier_id as enum ('common', 'uncommon', 'rare', 'epic', 'legendary');
  end if;
end
$$;

alter table brokers add column if not exists tier tier_id;

update brokers set tier = 'common' where id = 'PB-001';
update brokers set tier = 'uncommon' where id = 'PB-002';
update brokers set tier = 'common' where id = 'PB-003';
update brokers set tier = 'common' where id = 'PB-004';
update brokers set tier = 'common' where id = 'PB-005';
update brokers set tier = 'common' where id = 'PB-006';
update brokers set tier = 'common' where id = 'PB-007';
update brokers set tier = 'common' where id = 'PB-008';
update brokers set tier = 'uncommon' where id = 'PB-009';
update brokers set tier = 'uncommon' where id = 'PB-010';
update brokers set tier = 'rare' where id = 'PB-011';
update brokers set tier = 'uncommon' where id = 'PB-012';
update brokers set tier = 'uncommon' where id = 'PB-013';
update brokers set tier = 'common' where id = 'PB-014';
update brokers set tier = 'common' where id = 'PB-015';
update brokers set tier = 'common' where id = 'PB-016';
update brokers set tier = 'uncommon' where id = 'PB-017';
update brokers set tier = 'common' where id = 'PB-018';
update brokers set tier = 'common' where id = 'PB-019';
update brokers set tier = 'common' where id = 'PB-020';
update brokers set tier = 'common' where id = 'PB-021';
update brokers set tier = 'common' where id = 'PB-022';
update brokers set tier = 'rare' where id = 'PB-023';
update brokers set tier = 'common' where id = 'PB-024';

-- Founding floor: common 16, uncommon 6, rare 2.
